		-- billing > Price check > item
		SELECT ITEM.ITEM_ID
			, ASSETS.ASSET_TYPE_CD
			, ASSETS_TYPE.CODE_NAME ASSET_TYPE_NM
			, GODS.SRVC_ID
			, CTGR.SRVC_CTGR_NM
			, PRIC.*
			, PRIC_TYPE.CODE_NAME PRIC_TYPE_NM
			, ITEM.CNTS_NAME
		FROM TB_UAST_ITEM ITEM
			, TB_UAST_ASSETS ASSETS
			, TB_UAST_CODE ASSETS_TYPE
			, TB_UAST_GODS GODS
			, TB_UAST_SRVC_CTGR CTGR
			, TB_UAST_PRIC PRIC
			, TB_UAST_CODE PRIC_TYPE
		WHERE 1 = 1
		AND ITEM.DEL_YN = 'N'
		AND ASSETS.ASSET_ID LIKE '%'	-- terms ASSETS TYPE, need to change like to = --> 
		AND ASSETS.ASSET_ID = ITEM.ASSET_ID
		AND ASSETS.ASSET_TYPE_CD = ASSETS_TYPE.COMMON_CODE_ID
		AND ITEM.GODS_ID = GODS.GODS_ID
		AND GODS.SRVC_ID = CTGR.SRVC_ID
		AND CTGR.SRVC_ID LIKE '%'	-- terms service catagory, need to change like to = or in	-->
		AND ITEM.CNTS_NAME LIKE '%'	-- terms item name	-->
		AND ITEM.ITEM_ID = PRIC.TAGET_ID
		AND PRIC.PRIC_TYPE = PRIC_TYPE.COMMON_CODE_ID
		
		-- billing > Price check > Product
		SELECT GODS.SRVC_ID
			, GODS.GODS_ID
			, CTGR.SRVC_CTGR_NM
			, PRIC.*
			, GODS_DVSN_CD.CODE_NAME GODS_DVSN_NM	-- need to check sub_code_id
			, GODS.GODS_NAME
			, PRIC_TYPE.CODE_NAME PRIC_TYPE_NM
		FROM TB_UAST_GODS GODS
			, TB_UAST_SRVC_CTGR CTGR
			, TB_UAST_PRIC PRIC
			, TB_UAST_CODE GODS_DVSN_CD
			, TB_UAST_CODE PRIC_TYPE
		WHERE 1 = 1
		AND GODS.DEL_YN = 'N'
		AND GODS.SRVC_ID = CTGR.SRVC_ID
		AND CTGR.SRVC_ID LIKE '%'	-- terms service catagory, need to change like to = or in	-->
		AND GODS.GODS_NAME LIKE '%'	-- terms Product name	-->
		AND GODS.GODS_ID = PRIC.TAGET_ID
		AND GODS.GODS_DVSN = GODS_DVSN_CD.COMMON_CODE_ID
		AND PRIC.PRIC_TYPE = PRIC_TYPE.COMMON_CODE_ID
		
SELECT *
FROM TB_UAST_PRIC
