package com.skt.mars.adm.rm;

import com.skt.mars.adm.cm.RecordInfo;

/*
CREATE TABLE TB_UAST_BOARD
(
	-- BOARD_ID
	BOARD_ID VARCHAR(20) NOT NULL COMMENT 'BOARD_ID',
	-- BOARD_SUBJ
	BOARD_SUBJ VARCHAR(100) COMMENT 'BOARD_SUBJ',
	-- BOARD_CONT
	BOARD_CONT VARCHAR(2000) COMMENT 'BOARD_CONT',
	FRST_RGST_DT TIMESTAMP NOT NULL COMMENT 'FRST_RGST_DT',
	FRST_RGST_USER_ID VARCHAR(20) NOT NULL COMMENT 'FRST_RGST_USER_ID',
	LAST_CRCT_DT TIMESTAMP NOT NULL COMMENT 'LAST_CRCT_DT',
	LAST_CRCT_USER_ID VARCHAR(20) NOT NULL COMMENT 'LAST_CRCT_USER_ID',
	PRIMARY KEY (BOARD_ID)
) COMMENT = 'TB_UAST_BOARD';

 */

/**
 * PC모니터링
 * 
 * @author jseon
 * @version
 * @since
 * @created 2012. 01. 22.
 */

public class PCMonitoring extends RecordInfo{

}
